import { NextPage } from "next";
import Head from "next/head";
import { useAuthRequired } from "packages/state/features/auth/authHooks";

const Home: NextPage = () => {
  // useAuthRequired("/login", "/report");

  return (
    <div>
      <Head>
        <title>Tella Web 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossOrigin=""/>
        <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
      integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
      crossOrigin=""></script> */}
      </Head>
      <main></main>
    </div>
  );
};

export default Home;
